### ISSUE TITLE
Cant compile using windows 1903 (10.0.18362.1)

### ISSUE THREAD

**Issue by Enzodati122** [Alex3434/wmi-static-spoofer#16]
Can someone help me as well, getting compilation errors. I'm already using offsets and structs for windows 1903 (got those from the source link) but cant compile

![offset](https://github.com/Alex3434/wmi-static-spoofer/assets/162061880/4b9accc2-9f69-4158-8739-32a841e0cdf0)

![erro](https://github.com/Alex3434/wmi-static-spoofer/assets/162061880/0306b2e5-644d-4359-8241-797ea0e94af2)
